### ISSUE TITLE
DemoS(7–12) errors

### ISSUE THREAD

**Issue by olejandro** [etsap-TIMES/times-excel-reader#98]
> You can see the output of GAMS here:

Thanks.  I can see that the errors (for Demos7 at least) were not at all order issues, but quite some different kind of errors:  
1)  TRACO2 was not defined as a `COM_GRP` at all (domain). All commodities must be.
2)  `COM_STEP` parameters were written out without any commodity index
3)  The UC name 'UC_GrowthOfNewCars' was not defined as an `UC_N` at all (domain)

_Originally posted by @Antti-L in https://github.com/etsap-TIMES/times-excel-reader/issues/95#issuecomment-1658216131_

**Comment by Antti-L** [comment]
**Comment**:  DemoS_7 was referred to in the original post above, because that was the first Demo case mentioned as having domain violation errors in the Benchmark runs.  However, later I had a look also at the other Demos having errors (DemoS_8 to DemoS_12), and as far as I could see, all the domain violation errors in those other cases were likewise of those three types stated above:  Commodities not being defined as COM_GRP,  user constraint names not being defined as UC_N, and invalid domain indexes being defined for COM_STEP.

**Comment by Antti-L** [comment]
Great, the incorrect mappings mentioned above have apparently now been fixed.
How about the missing members in the domains (`COM_GRP` and `UC_N`)?  
Have they also been fixed by now?  I could myself not see anything in the most recent code diffs that would confirm those domain problems having been fixed yet.  And I could neither find any **artifacts** from the test runs (e.g. the listing files and DD files generated from the DemoS), such that I could check how the code is performing now.  Are the most recent benchmark output files always available somewhere, and if not, why is that?

**Comment by olejandro** [comment]
No, looks like missing members in `COM_GRP` and `UC_N` are still missing.

**Comment by olejandro** [comment]
Looks like `UC_GrowthOfNewCars` is missing because no `UC_Desc` is specified and we don't fill it at the moment. @siddharth-krishna we can handle this later together with other defaults in one of the json files.

**Comment by Antti-L** [comment]
Ok, thanks @olejandro. Then the only thing left to do (for closing this issue), would be to add also the missing UC names into the domain `SET UC_N`.  I guess adding into that set any UC name encountered in the UC_N column of any `~UC_T` or `~TFM_INS / DINS` table would suffice...

**Comment by olejandro** [comment]
Well, actually it is not the issue. All `UC_N` are currently read. However when outputing the sets, no missing values in a record are allowed, so `UC_N` without `UC_Desc` are dropped. It is easy to fix. We'll populate missing `UC_Desc` with corresponding `UC_N` values. We are currently developing a general transparent approach for specifying this kind of behaviour, so that's why I am a bit reluctant to do it already. At the same time, it is not much more than just one line of code, so maybe makes sense to add it now...

Regarding user constraint input via `~TFM_INS / DINS`, it should only be allowed if there is an existing constraint defined via `~UC_T`, should it not? I must admit I have not followed the development in this respect. Some years ago, when I tried to change a constraint via `~TFM_INS` it was not yet supported.

**Comment by siddharth-krishna** [comment]
@Antti-L the artifacts were only generated for that PR where we were trying to fix the gams issues -- I did not enable it by default because it makes the CI much slower. If you have the time and want to try running the tool on the benchmarks yourself, you can take a look at [ci.yml](https://github.com/etsap-TIMES/times-excel-reader/blob/main/.github/workflows/ci.yml) which has all the steps needed to install the tool and run the benchmarks. I'd also be happy to answer any questions or walk you through the steps in more detail, and your feedback installing / running the tool would be very helpful.

**Comment by siddharth-krishna** [comment]
But you can still see the output of GAMS on the Demo models under the Actions tab of GitHub: (perhaps search for "Starting compilation" or something since this step has a massive output)
<img width="1208" alt="image" src="https://github.com/etsap-TIMES/times-excel-reader/assets/10712637/cfab7727-27df-42a8-8d04-b09bc8314002">
